export namespace req {
    export enum type {
        ON,
        ONCE
    }

    export enum callType {
        GET = "get",
        POST = "post",
        PUT = "put",
        DELETE = "delete",
        PATCH = "patch"
    }

    export enum HTTPerror {
        _100 = "Continue",
        _101 = "Switching Protocols",
        _102 = "Processing",
        _103 = "Early Hints",

        _200 = "OK",
        _201 = "Created",
        _202 = "Accepted",
        _203 = "Non-Authoritative Information",
        _204 = "No Content",
        _205 = "Reset Content",
        _206 = "Partial Content",
        _207 = "Multi-Status",
        _208 = "Already Reported",
        _210 = "Content Different",
        _226 = "IM Used",

        _300 = "Multiple Choices",
        _301 = "Moved Permanently",
        _302 = "Found",
        _303 = "See Other",
        _304 = "Not Modified",
        _305 = "Use Proxy",
        _306 = "Switch Proxy",
        _307 = "Temporary Redirect",
        _308 = "Permanent Redirect",
        _310 = "Too many Redirects",

        _400 = "Bad Request",
        _401 = "Unauthorized",
        _402 = "Payment Required",
        _403 = "Forbidden",
        _404 = "Not Found",
        _405 = "Method Not Allowed",
        _406 = "Not Acceptable",
        _407 = "Proxy Authentication Required",
        _408 = "Request Timeout",
        _409 = "Conflict",
        _410 = "Gone",
        _411 = "Length Required",
        _412 = "Precondition Failed",
        _413 = "Payload Too Large",
        _414 = "URI Too Long",
        _415 = "Unsupported Media Type",
        _416 = "Range Not Satisfiable",
        _417 = "Expectation Failed",
        _418 = "I'm a teapot",
        _419 = "Page Timeout",
        _421 = "Misdirected Request",
        _422 = "Unprocessable Entity",
        _423 = "Locked",
        _424 = "Method Failure",
        _425 = "Too Early",
        _426 = "Upgrade Required",
        _427 = "Invalid digital signature",
        _428 = "Precondition Required",
        _429 = "Too Many Requests",
        _431 = "Request Header Fields Too Large",
        _449 = "Retry With",
        _450 = "Blocked by Parental Controls",
        _451 = "Unavailable For Legal Reasons",
        _456 = "Unrecoverable Error",

        _500 = "Internal Server Error",
        _501 = "Not Implemented",
        _502 = "Bad Gateway",
        _503 = "Service Unavailable",
        _504 = "Gateway Timeout",
        _505 = "HTTP Version Not Supported",
        _506 = "Variant Also Negotiates",
        _507 = "Insufficient Storage",
        _508 = "Loop Detected",
        _509 = "Bandwidth Limit Exceeded",
        _510 = "Not Extended",
        _511 = "Network Authentication Required",
        _520 = "Unknown Error",
        _521 = "Web Server Is Down",
        _522 = "Connection Timed Out",
        _523 = "Origin Is Unreachable",
        _524 = "A Timeout Occurred",
        _525 = "SSL Handshake Failed",
        _526 = "Invalid SSL Certificate",
        _527 = "Railgun Error",
    }
}