export namespace req {
    export enum type {
        PUBLIC,
        PRIVATE
    }

    export enum callType {
        GET = "get",
        POST = "post",
        PUT = "put",
        PATCH = "patch",
        DELETE = "delete"
    }

    export enum HTTPerror {
        Continue = 100,
        SwitchingProtocols = 101,
        Processing = 102,
        EarlyHints = 103,

        OK = 200,
        Created = 201,
        Accepted = 202,
        NonAuthoritativeInformation = 203,
        NoContent = 204,
        ResetContent = 205,
        PartialContent = 206,
        MultiStatus = 207,
        AlreadyReported = 208,
        ContentDifferent = 210,
        IMUsed = 226,
        
        MultipleChoices = 300,
        MovedPermanently = 301,
        Found = 302,
        SeeOther = 303,
        NotModified = 304,
        UseProxy = 305,
        SwitchProxy = 306,
        TemporaryRedirect = 307,
        PermanentRedirect = 308,
        TooManyRedirects = 310,
        
        BadRequest = 400,
        Unauthorized = 401,
        PaymentRequired = 402,
        Forbidden = 403,
        NotFound = 404,
        MethodNotAllowed = 405,
        NotAcceptable = 406,
        ProxyAuthenticationRequired = 407,
        RequestTimeout = 408,
        Conflict = 409,
        Gone = 410,
        LengthRequired = 411,
        PreconditionFailed = 412,
        PayloadTooLarge = 413,
        URITooLong = 414,
        UnsupportedMediaType = 415,
        RangeNotSatisfiable = 416,
        ExpectationFailed = 417,
        ImATeapot = 418,
        PageTimeout = 419,
        MisdirectedRequest = 421,
        UnprocessableEntity = 422,
        Locked = 423,
        MethodFailure = 424,
        TooEarly = 425,
        UpgradeRequired = 426,
        InvalidDigitalSignature = 427,
        PreconditionRequired = 428,
        TooManyRequests = 429,
        RequestHeaderFieldsTooLarge = 431,
        RetryWith = 449,
        BlockedByParentalControls = 450,
        UnavailableForLegalReasons = 451,
        UnrecoverableError = 456,
        SSLCertificateError = 495,
        SSLCertificateRequired = 496,
        HTTPRequestSentToHTTPSPort = 497,
        TokenExpired = 498,
        TokenRequired = 499,

        InternalServerError = 500,
        NotImplemented = 501,
        BadGateway = 502,
        ServiceUnavailable = 503,
        GatewayTimeout = 504,
        HTTPVersionNotSupported = 505,
        VariantAlsoNegotiates = 506,
        InsufficientStorage = 507,
        LoopDetected = 508,
        BandwidthLimitExceeded = 509,
        NotExtended = 510,
        NetworkAuthenticationRequired = 511,
        UnknownError = 520,
        WebServerIsDown = 521,
        ConnectionTimedOut = 522,
        OriginIsUnreachable = 523,
        ATimeoutOccurred = 524,
        SSLHandshakeFailed = 525,
        InvalidSSLCertificate = 526,
        RailgunError = 527
    }
}